// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgIZo_bEKkXEOuueDrLdGdeL9MJUt-OYE',
    appId: '1:474327512197:web:a580e5f46e0e18c6c365ec',
    messagingSenderId: '474327512197',
    projectId: 'treade-581e9',
    authDomain: 'treade-581e9.firebaseapp.com',
    storageBucket: 'treade-581e9.firebasestorage.app',
    measurementId: 'G-T5R07NZNTT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUJK0Jn_YT8-NGW4LBpPMnRr15klbMtIE',
    appId: '1:474327512197:android:0fe4fa71db5d12c4c365ec',
    messagingSenderId: '474327512197',
    projectId: 'treade-581e9',
    storageBucket: 'treade-581e9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMtkSeD4n4I0Le1-V9zU8qGjRSd3_qiV8',
    appId: '1:474327512197:ios:f828835f1aab5712c365ec',
    messagingSenderId: '474327512197',
    projectId: 'treade-581e9',
    storageBucket: 'treade-581e9.firebasestorage.app',
    androidClientId: '474327512197-q1j8hu71d35ju6mbnvv1ddvvhu8qqsdv.apps.googleusercontent.com',
    iosClientId: '474327512197-ptca88fn69s3md5nc26m6h4i86rv3q0g.apps.googleusercontent.com',
    iosBundleId: 'com.example.tread256',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMtkSeD4n4I0Le1-V9zU8qGjRSd3_qiV8',
    appId: '1:474327512197:ios:f828835f1aab5712c365ec',
    messagingSenderId: '474327512197',
    projectId: 'treade-581e9',
    storageBucket: 'treade-581e9.firebasestorage.app',
    androidClientId: '474327512197-q1j8hu71d35ju6mbnvv1ddvvhu8qqsdv.apps.googleusercontent.com',
    iosClientId: '474327512197-ptca88fn69s3md5nc26m6h4i86rv3q0g.apps.googleusercontent.com',
    iosBundleId: 'com.example.tread256',
  );
}
